In [70]:
import numpy as np

In [71]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

In [72]:
def sigmoid_derivative(x):
    return x*(1-x)

In [73]:
def train(train_inputs,train_outputs,num_epoch,wo):
    for i in range(num_epoch):
        output = __sigmoid(np.dot(train_inputs,wo))
        error = train_outputs-output
        adjustment = np.dot(train_inputs.T,error*__sigmoid_derivative(output))
        wo += adjustment

In [75]:
training_set_inputs = np.array([[0, 0, 1], [1, 1, 1], [1, 0, 1], [0, 1, 1]])
training_set_outputs = np.array([[0, 1, 1, 0]]).T
wo = np.random.random((3,1))-1
wo

array([[-0.03075143],
       [-0.80422254],
       [-0.44864169]])

In [79]:
train(training_set_inputs,training_set_outputs,1000000,wo)

In [80]:
wo

array([[15.01613883],
       [-0.20311639],
       [-7.30503377]])

In [81]:
__sigmoid(np.dot(np.array([1,1,0]),wo))

array([0.99999963])